# Generated by Django 4.1.5 on 2023-01-31 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_team_userprofile_team"),
        ("projects", "0002_alter_project_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="projects",
                to="accounts.team",
            ),
        ),
    ]
