# Generated by Django 4.1.5 on 2023-01-31 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_userprofile_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(blank=True, default=None, upload_to=None),
        ),
    ]
