# Generated by Django 4.1.5 on 2023-02-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_userprofile_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="picture",
            field=models.ImageField(
                default=None, null=True, upload_to="images/team"
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(
                default=None, null=True, upload_to="images/profile"
            ),
        ),
    ]
